# Research Skills: Image Analysis - Entrance Assignment 
Sharon Ong, Department of Cognitive Science and Artificial Intelligence – Tilburg University

Academic Year 2023-2024

This entrace assignment does not count towards your final grade. It is used for you to assess whether you are able to manage with the coursework. No resits will be provided as this assignment does not count towards your final grade. 

This assignment is due on Saturday, 3rd February, 2024. 

# Numpy 

Numpy (https://numpy.org/) is one of the fundamental packages for scientific computing in Python. It contains functionality for multidimensional arrays, high-level mathematical functions and pseudorandom number generators. 

Different Python libraries can be used for basic image manipulation. Almost all of the libraries store an image in numpy ndarray (a 2-D array for grayscale and a 3-D array for an RGB image, for example). 

Having a solid understanding of numpy is necessary if you want to work on image analysis projects. In this course, we will mainly use the scikit-image package to build image analysis applications. This works heavily with numpy as well.  

Numpy provides the excellent ndarray objects, short for n-dimensional arrays. In a ‘ndarray’ object, aka ‘array’, you can store multiple items of the same data type. There are facilities around the array object that makes numpy so convenient for performing math and data manipulations.

Complete the following exercises with numpy. 

1. Create a 1D numpy array with the contents of list1 and print the result 

In [2]:
import numpy as np

list1 = [0,1,2,3,4]
# 
# Your code goes here 
# 

2. Create a 2D array of 2 rows and 3 columns with numbers of your choice. 
3. Increase every number in the array by 2 (add 2 to every number in the array). Print the results 

In [ ]:
#
# Your code goes here 
#

4. Print the shape, data types, size and number of dimensions 

In [ ]:
#
# Your code goes here 
#

5.  Create a numpy array which will print the following output 
 
#> ['1' '2' 'a' 'b']

In [ ]:
#
# Your code goes here 
#

6. Reverse the rows of the following numpy array 

In [4]:
list = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr = np.array(list, dtype='float')
print(arr)
#
# Your code goes here 
#

[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [5. 6. 7. 8.]]


7. Compute the mean and standard deviation of the numpy array (arr)

In [ ]:
#
# Your code goes here 
#

8. Compute the minimum values row wise or column wise (use the np.amin version)

In [ ]:
#
# Your code goes here 
#

9. Flatten the numpy array 'arr'. You can use the flatten() or the ravel() method
These are 2 popular ways to implement flattening. The difference between ravel and flatten is, the new array created using ravel is actually a reference to the parent array. So, any changes to the new array will affect the parent as well. But is memory efficient since it does not create a copy.

In [ ]:
#
# Your code goes here 
#
# transpose the image

# 

##  matplotlib 
matplotlib is the primary scientific plotting library in Python, providing functions for making publication-quality visualizations. You can show figures directly in browser using the "%matplotlib notebook" or "%matlplotlib inline" commands. You can create the plot with generated arrays 'x' and 'y'. (Plot x vs y), with different markers and label the x and y axis. Run the code below: 

In [ ]:
%matplotlib notebook
import matplotlib.pyplot as plt

# Generate a sequence of numbers from -10 to 10 with 100 steps in between
x = np.linspace(-10, 10, 100)
# Create a second array using sine
y = np.sin(x)
# The plot function makes a line chart of one array against another
plt.figure()
plt.plot(x, y, 'r.')
plt.xlabel('x')
plt.ylabel('y')
plt.figure()
plt.plot(x, 2*y, 'b+')
plt.xlabel('x')
plt.ylabel('y')